apiVersion: batch/v1
kind: Job
metadata:
  name: cvmfs-all-repos
spec:
  template:
    spec:
      containers:
        - name: idle
          image: nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c", "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "1"
              memory: "4Gi"
          volumeMounts:
            - name: my-cvmfs
              mountPath: /my-cvmfs
              # CVMFS automount volumes must be mounted with HostToContainer mount propagation.
              mountPropagation: HostToContainer
      volumes:
        - name: my-cvmfs
          persistentVolumeClaim:
            claimName: cvmfs